# JWT
jwt.expire.hours=2
jwt.token.private_key=keys/private_key.der
jwt.token.public_key=keys/public_key.der

# RabbitMQ Server properties
spring.rabbitmq.host= 192.168.100.7
spring.rabbitmq.port= 5672
spring.rabbitmq.username= admin
spring.rabbitmq.password= citK19c3
# AMQP properties
rabbitmq.queueName=ldap.users
rabbitmq.topicName=ldap
rabbitmq.routingKey=ldap.users.#

# LDAP
adresse_ip=176.31.233.13
admin_password=DreJhM34opAE3njbFbps
ldap_port=3589

base_dn=dc=montpellier,dc=lan
ou_utilisateurs=ou=Pedago,ou=Utilisateurs
ou_groups=ou=Groupes
groupe_etudiants=Etudiants

users_ldap_directory=
# users_ldap_directory=/home/users/ldap

# SSL
# The format used for the keystore. It could be set to JKS in case it is a JKS file
#server.ssl.key-store-type=PKCS12
# The path to the keystore containing the certificate
#server.ssl.key-store=classpath:keystore/ws_users.p12
# The password used to generate the certificate
#server.ssl.key-store-password=abcd4ABCD
# The alias mapped to the certificate
#server.ssl.key-alias=ws_users